MAINT: hnn_docker.sh doesn't require docker compose
Switch from using docker-compose to using regular docker commands.
Also prepare for running hnn_docker.sh with a windows container and
preliminary support for WSL.

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -89,14 +89,15 @@ matrix:
           - NEURON_VERSION=7.7
 
 before_install:
-  - set -e
-  - |
+  - set -e  # error on any command failure
+  - | # function exports
+    echo "Exporting utility functions"
+
     export TRAVIS_TESTING=1
 
+    export LOGFILE="hnn_travis.log"
     source scripts/utils.sh
     source scripts/docker_functions.sh
-    export LOGFILE="hnn_travis.log"
-    set_globals
 
     # override cleanup function in docker_functions.sh
     function cleanup {
@@ -119,6 +120,9 @@ before_install:
 
     export -f cleanup
 
+    # use some functions to set $docker_cmd and $CONTAINER_TYPE
+    set_globals
+
     export DOCKER_IMAGE_NAME="jonescompneurolab/hnn:master"
     export BASE_QEMU_OPTS="--disable-cocoa --disable-curses --disable-vnc --disable-vde \
                           --disable-pie --disable-libusb --disable-hax --disable-kvm \
@@ -131,7 +135,19 @@ before_install:
 
   - |
     if [ "${TRAVIS_OS_NAME}" == "osx" ]; then  # install osx prerequisites
+      echo "Installing macOS prerequisites"
+
       scripts/setup-travis-mac.sh
+      export PATH=${HOME}/miniconda/bin:$PATH
+      export PATH=$PATH:/Applications/NEURON-${NEURON_VERSION}/nrn/x86_64/bin
+      export PYTHONPATH=/Applications/NEURON-${NEURON_VERSION}/nrn/lib/python:$PYTHONPATH
+      export PATH=$PATH:/Applications/Docker.app/Contents/Resources/bin
+      export PYTHON=python3
+      eval "$(docker-machine env default)"
+
+      # check container type
+      find_program_print docker && export docker_cmd || script_fail
+      get_docker_container_type && export CONTAINER_TYPE || script_fail
 
       # set up DISPLAY and make sure that xquartz is ready
       check_xquartz_listening || {
@@ -141,17 +157,16 @@ before_install:
       # accept TCP connections in hnn_docker.sh later
       xset -display $DISPLAY -q > /dev/null
 
-      export PATH=${HOME}/miniconda/bin:$PATH
-      export PATH=$PATH:/Applications/NEURON-${NEURON_VERSION}/nrn/x86_64/bin
-      export PYTHONPATH=/Applications/NEURON-${NEURON_VERSION}/nrn/lib/python:$PYTHONPATH
-      export PATH=$PATH:/Applications/Docker.app/Contents/Resources/bin
-      export PYTHON=python3
-      eval "$(docker-machine env default)"
-
       source activate hnn && echo "activated conda HNN environment"
     fi
-  - |
-    if [ "${TRAVIS_OS_NAME}" == "windows" ]; then  # install windows prerequisites
+  - | # windows
+    if [ "${TRAVIS_OS_NAME}" == "windows" ]; then
+      echo "Installing windows prerequisites"
+
+      # check container type
+      find_program_print docker && export docker_cmd || script_fail
+      get_docker_container_type && export CONTAINER_TYPE || script_fail
+
       scripts/setup-travis-windows.sh
 
       # add miniconda python to the path
@@ -166,27 +181,38 @@ before_install:
       export NEURONHOME=/c/nrn
       export PYTHON=python
     fi
-  - |
+  - | # Linux
     if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
+      echo "Installing Linux prerequisites"
+
+      # check container type
+      find_program_print docker && export docker_cmd || script_fail
+      get_docker_container_type && export CONTAINER_TYPE || script_fail
+
       echo "Starting fake Xserver"
       Xvfb :0 -listen tcp -screen 0 1024x768x24 > /dev/null &
+
       export DISPLAY=:0
       export PATH=/usr/bin:/usr/local/bin:$PATH
+
       echo "Starting Ubuntu install script"
-      bash -xe ./installer/ubuntu/installer.sh
-      echo "Install finished"
+      installer/ubuntu/installer.sh || script_fail
+
       NLOPT_LIB=$(ls -d $HOME/.local/lib/python*/site-packages)
       echo $NLOPT_LIB
       export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$NLOPT_LIB
       export PYTHON=python3
+
+      # test X server
       xset -display $DISPLAY -q > /dev/null;
     fi
 
 install:
-  - if [[ ! "${TRAVIS_OS_NAME}" == "windows" ]]; then
+  - | # for mac build HNN .mod files
+    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
       make;
     fi;
-  - |
+  - | # start the docker image build on linux
     if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
       if [[ "$TRAVIS_PULL_REQUEST" =~ "false" ]]; then
         SOURCE_REPO="https://github.com/${TRAVIS_REPO_SLUG}.git"
@@ -205,11 +231,9 @@ install:
   - pip install flake8 pytest pytest-cov coverage coveralls mne
 
 script:
-  - echo "Running Python tests" && py.test tests/
-  - echo "Testing GUI on host OS" && $PYTHON hnn.py
-  - |
+ - | # wait for docker image to be ready for tests
     if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
-      echo "Waiting on docker build:"
+      echo "Waiting on docker build"
       cat docker_build.txt
       while ! cat docker_build.txt|grep "Successfully built"; do
         if cat docker_build.txt|grep "Failed build"; then
@@ -221,36 +245,56 @@ script:
       done
       tail -1 docker_build.txt
     else
+      echo "Waiting for docker image to be loaded"
       while ! test -e $HOME/docker_image_loaded; do
-        echo "Sleeping for 10s while waiting for docker image download to complete"
-        sleep 10
+        sleep 1
       done
     fi
-  - |
-    if [[ "${TRAVIS_OS_NAME}" = "windows" ]]; then
-      echo "Testing GUI in docker without ssh as user 'test user'"
+  - | # test HNN using Docker without SSH
+    echo "Testing GUI in docker without ssh..."
+    if [[ "${CONTAINER_TYPE}" = "windows" ]]; then
+      echo "Running as user 'test user'"
       powershell -executionpolicy bypass -File "scripts\start-test-as-user.ps1"
     else
-      echo "Testing GUI in docker without ssh"
       USE_SSH=0 ./hnn_docker.sh start || script_fail
     fi
-  - |
-    if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
-      echo "Testing MPI in docker"
-      make clean
-      # only run on linux because it's not virtualized through qemu
-      timeout 120 docker exec hnn_container bash -c "sudo apt-get install --no-install-recommends -y \
-        make gcc libc6-dev libtinfo-dev libncurses-dev libx11-dev libreadline-dev"
-      timeout 300 docker exec -u $UID:hnn_group hnn_container bash -c "make && source /home/hnn_user/hnn_envs && \
-        mpiexec -np 2 --oversubscribe nrniv -mpi -python run.py param/default.param && echo finished simulation" || { \
+  - | # Testing hnn_docker.sh upgrade command
+    echo "Testing hnn_docker.sh upgrade"
+    # if [[ "${TRAVIS_OS_NAME}" = "linux" ]]; then
+    #   ./hnn_docker.sh upgrade || script_fail
+    # else
+    #   echo "Skipping"
+    # fi
+  - | # For linux containers (mac/windows/linux OS), start HNN with docker using ssh
+    if [[ ! "${CONTAINER_TYPE}" = "windows" ]]; then
+      echo "Testing GUI in docker with ssh"
+      USE_SSH=1 ./hnn_docker.sh start || script_fail
+    fi
+  - | # test running a MPI simulation within container
+    echo "Testing MPI in docker..."
+    if [[ $TRAVIS_OSX_IMAGE == "xcode8" ]] || [[ $TRAVIS_OSX_IMAGE == "xcode9.2" ]]; then
+      # tests on mac take a long time. sierra and el capitan are close to maximum build times
+      echo "Skipping"
+    else
+      if [[ "$CONTAINER_TYPE" == "linux" ]]; then
+        timeout 120 docker exec hnn_container bash -c "sudo apt-get install --no-install-recommends -y \
+          make gcc libc6-dev libtinfo-dev libncurses-dev libx11-dev libreadline-dev"
+        timeout 120 docker exec -u hnn_user hnn_container bash -c "make clean && make"
+      fi
+      timeout 300 docker exec -u hnn_user hnn_container bash -c "source /home/hnn_user/hnn_envs && \
+        mpiexec -np 2 nrniv -mpi -python run.py && echo finished simulation" || { \
           echo -e "\nMPI test failed\n"
           docker ps -a | grep hnn_container
           false
-        }
-      echo "Testing hnn_docker.sh upgrade" && ./hnn_docker.sh upgrade || script_fail
+        } || script_fail
     fi
-  - |
-    if [[ ! "${TRAVIS_OS_NAME}" = "windows" ]]; then
-      echo "Testing GUI in docker with ssh" && USE_SSH=1 ./hnn_docker.sh start || script_fail
-      echo "Testing hnn_docker.sh uninstall command" && ./hnn_docker.sh uninstall || script_fail
-    fi
+  - | # Test hnn_docker.sh uninstall command
+    echo "Testing hnn_docker.sh uninstall command"
+    ./hnn_docker.sh uninstall || script_fail
+  - | # Check that the GUI starts on host OS
+    echo "Testing GUI on host OS..."
+    $PYTHON hnn.py
+   - | # Run py.test that includes running a simulation and verifying results
+    echo "Running Python tests..."
+    py.test tests/
+
